name: secrets sync
on:
  push:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Synchronize secrets
      uses: google/secrets-sync-action@master
      with:
        dry_run: false
        github_token: ${{ secrets.GIT_S_SYNC }}
        secrets: |
          ^GIT_PAT$
          ^GPG_.*
        repositories: |
          ^tech10/ipaddr$
